name: Github Pages CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # Allows to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.5'

      - name: Get dependencies
        run: go mod tidy

      - name: Compile static files
        run: |
          cd example
          go run ../cmd -config="config.json"
          chmod -R a+rX ./output

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: example/output/

  deploy:
      needs: build
  
      permissions:
        pages: write
        id-token: write
  
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
  
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
          with:
            artifact_name: example-pages
